"""
Gateway Pairing Helper Script
Simplifies pairing your local server with the production cloud
"""
import requests
import uuid
from django.core.management.base import BaseCommand

CLOUD_URL = "http://35.209.239.164"

class Command(BaseCommand):
    help = 'Pair local gateway with production cloud server'

    def add_arguments(self, parser):
        parser.add_argument('pairing_code', type=str, help='8-digit pairing code from mobile app')

    def handle(self, *args, **options):
        pairing_code = options['pairing_code']
        
        # Generate gateway UUID
        gateway_uuid = str(uuid.uuid4())
        
        self.stdout.write(f"\n{'='*60}")
        self.stdout.write(self.style.SUCCESS('🔗 Gateway Pairing'))
        self.stdout.write(f"{'='*60}")
        self.stdout.write(f"\nPairing Code: {pairing_code}")
        self.stdout.write(f"Gateway UUID: {gateway_uuid}")
        
        # Complete pairing with cloud
        self.stdout.write(f"\n📡 Connecting to cloud server...")
        
        try:
            response = requests.post(
                f"{CLOUD_URL}/api/gateways/complete-pairing/",
                json={
                    "pairing_code": pairing_code,
                    "gateway_uuid": gateway_uuid,
                    # home_id is generated by cloud from pairing code
                    "name": f"Gateway {gateway_uuid[:8]}",
                    "version": "1.0.0"
                },
                timeout=15
            )
            
            if response.status_code == 201:
                data = response.json()
                cloud_home_id = data['home_id']  # Cloud assigns home_id
                secret = data['secret']
                
                self.stdout.write(self.style.SUCCESS('\n✅ Gateway paired successfully!'))
                self.stdout.write(f"\n{'='*60}")
                self.stdout.write(self.style.WARNING('SAVE THESE CREDENTIALS:'))
                self.stdout.write(f"{'='*60}")
                self.stdout.write(f"\nCLOUD_GATEWAY_ID={cloud_home_id}")
                self.stdout.write(f"CLOUD_GATEWAY_SECRET={secret}")
                self.stdout.write(f"\n{'='*60}")
                
                # Write to .env file
                env_content = f"""
# Cloud Configuration (Generated by pairing)
CLOUD_ENABLED=true
CLOUD_BRIDGE_URL=ws://{CLOUD_URL.replace('http://', '')}/ws/gateway/
CLOUD_GATEWAY_ID={cloud_home_id}
CLOUD_GATEWAY_UUID={gateway_uuid}
CLOUD_GATEWAY_SECRET={secret}
"""
                
                try:
                    with open('.env', 'a') as f:
                        f.write(env_content)
                    self.stdout.write(self.style.SUCCESS('\n✅ Credentials added to .env file'))
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'\n⚠️  Could not write to .env: {e}'))
                    self.stdout.write(self.style.WARNING('Please add credentials manually'))
                
                self.stdout.write(self.style.SUCCESS('\n🎉 Pairing complete! Restart server to connect to cloud.'))
                
            else:
                self.stdout.write(self.style.ERROR(f'\n❌ Pairing failed: {response.status_code}'))
                self.stdout.write(response.text[:500])
                
        except requests.exceptions.RequestException as e:
            self.stdout.write(self.style.ERROR(f'\n❌ Connection error: {e}'))
        
        self.stdout.write("")
