# Generated by Django 5.2.9 on 2025-12-18 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_name', models.CharField(help_text='Must match ESPHome node name', max_length=100, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Board type, mac, ip, etc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('sensor', 'Sensor'), ('switch', 'Switch'), ('relay', 'Relay'), ('light', 'Light'), ('fan', 'Fan'), ('valve', 'Valve'), ('climate', 'Climate'), ('lock', 'Lock')], max_length=20)),
                ('subtype', models.CharField(blank=True, help_text='rgb, dimmer, speed, dht22, soil_moisture, etc', max_length=50)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='brightness, rgb, speed, modes, etc')),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('is_controllable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, help_text='temperature, humidity, state', max_length=50)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('==', '==')], max_length=5)),
                ('value', models.CharField(max_length=50)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.automation')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.JSONField(help_text="e.g. {state:'ON'} or {brightness:80}")),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.automation')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.home'),
        ),
        migrations.AddField(
            model_name='automation',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.home'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('room', 'Room'), ('zone', 'Zone'), ('field', 'Field'), ('greenhouse', 'Greenhouse')], max_length=20)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.home')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.CreateModel(
            name='OTAUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('firmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.firmware')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.home')),
            ],
        ),
        migrations.CreateModel(
            name='SceneAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.scene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EntityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.entity')),
            ],
            options={
                'unique_together': {('entity', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EntityStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'timestamp'], name='core_entity_entity__ce0dd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('family', 'Family'), ('guest', 'Guest')], max_length=10)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('home', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('device', 'name')},
        ),
    ]
