# Generated by Django 5.2.9 on 2025-12-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scene'),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='command',
            field=models.JSONField(blank=True, help_text="e.g. {state:'ON'} or {brightness:80}", null=True),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
    ]
