# Generated by Django 5.2.9 on 2025-12-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='home_identifier',
            field=models.CharField(default='home_test_1', help_text="String identifier for the home (e.g., 'home_test_1', '1')", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(blank=True, help_text='Optional link to Home object for backward compatibility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.home'),
        ),
        migrations.AlterField(
            model_name='device',
            name='node_name',
            field=models.CharField(help_text='Must match ESPHome node name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('home_identifier', 'node_name')},
        ),
    ]
