# Generated by Django 5.2.9 on 2025-12-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_home_identifier_alter_device_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('trigger_value', models.CharField(blank=True, max_length=255)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.automation')),
                ('trigger_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entity')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['-executed_at'], name='core_automa_execute_b92c9b_idx'), models.Index(fields=['automation', '-executed_at'], name='core_automa_automat_497f13_idx')],
            },
        ),
    ]
