# Generated by Django 5.2.9 on 2025-12-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_automationexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='cooldown_seconds',
            field=models.IntegerField(default=60, help_text='Minimum seconds between executions (prevents rapid re-triggering)'),
        ),
        migrations.AddField(
            model_name='automation',
            name='trigger_logic',
            field=models.CharField(choices=[('AND', 'All conditions must match'), ('OR', 'Any condition matches')], default='AND', help_text='How to combine multiple triggers', max_length=3),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='delay_seconds',
            field=models.IntegerField(default=0, help_text='Delay before executing this action (in seconds)'),
        ),
    ]
