# Generated by Django 5.2.9 on 2025-12-21 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_automation_cooldown_seconds_automation_trigger_logic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, unique=True)),
                ('average_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Power Profile',
                'verbose_name_plural': 'Device Power Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserEnergySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_rate_per_kwh', models.DecimalField(decimal_places=2, default=8.0, help_text="Cost per kWh in user's currency", max_digits=6)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Energy Settings',
                'verbose_name_plural': 'User Energy Settings',
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('on_duration_seconds', models.IntegerField(default=0, help_text='Total seconds device was on')),
                ('estimated_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to='core.entity')),
            ],
            options={
                'verbose_name': 'Energy Log',
                'verbose_name_plural': 'Energy Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['entity', 'date'], name='core_energy_entity__0952b5_idx'), models.Index(fields=['date'], name='core_energy_date_3117a6_idx')],
                'unique_together': {('entity', 'date')},
            },
        ),
    ]
