# Generated by Django 5.2.9 on 2025-12-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_scene_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtrigger',
            name='days_of_week',
            field=models.JSONField(blank=True, help_text='List of days: [0-6] where 0=Monday, 6=Sunday. Empty list = every day', null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='sun_event',
            field=models.CharField(blank=True, choices=[('sunrise', 'Sunrise'), ('sunset', 'Sunset'), ('dawn', 'Dawn'), ('dusk', 'Dusk'), ('noon', 'Solar Noon')], help_text='Astronomical event to trigger on', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='sun_offset',
            field=models.IntegerField(default=0, help_text='Offset in minutes (negative = before event, positive = after)'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='Time to trigger (HH:MM:SS)', null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('state', 'Entity State'), ('time', 'Time Schedule'), ('sun', 'Astronomical Event')], default='state', help_text='Type of trigger: state, time, or sun', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='elevation',
            field=models.IntegerField(default=0, help_text='Elevation in meters for accurate sun calculations'),
        ),
        migrations.AddField(
            model_name='home',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for sun calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for sun calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Timezone (e.g., 'Asia/Kolkata', 'America/New_York')", max_length=50),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='operator',
            field=models.CharField(blank=True, choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater or Equal'), ('<=', 'Less or Equal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
