# Generated by Django 5.2.9 on 2025-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_automationtrigger_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cloud_enabled',
            field=models.BooleanField(default=False, help_text='Whether cloud mode is enabled for this home'),
        ),
        migrations.AddField(
            model_name='home',
            name='cloud_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the cloud subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cloud_subscription_tier',
            field=models.CharField(choices=[('free', 'Free - Local Only'), ('basic', 'Basic - Cloud Access')], default='free', help_text='Subscription tier for cloud access', max_length=20),
        ),
    ]
